[package]
name = "elentium/elitedatastoreservice"
version = "1.5.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "server"
authors = ["IAMNOTULTRA3"]
exclude = ["selene.toml", "rokit.toml", ".gitignore"]
